#!/bin/bash

# Set Environment
export GOPATH=/home/mmiles/Software/ma/3rapp
export PATH=$NOGOPATH:$GOROOT/bin:$GOPATH/bin

# Change to project directory
cd ~/Software/ma/3rapp/src/github.com/MilesAheadLLC/3rapp

# Set RVM version
rvm use 1.9.3@3rapp

# Set node version
nvm use 0.10.29

